version: '3.8'

services:

  # backend:
  #   image: backend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 8080:8080
  #     - 9229:9229
  #   command: [ "node", "--inspect=0.0.0.0:9229", "index.js" ]

  bookrent:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: postgres
      POSTGRES_DB: bookrent
    ports:
      - 5432:5432
    volumes:
      - app_data:/var/lib/postgresql/data_app

volumes:
  app_data:
